// <auto-generated />
using System;
using BagdasKitapDunyasi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BagdasKitapDunyası.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511003409_SiparisTablosuEklendi")]
    partial class SiparisTablosuEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Roman",
                            Slug = "roman"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bilim Kurgu",
                            Slug = "bilim-kurgu"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Tarih",
                            Slug = "tarih"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Felsefe",
                            Slug = "felsefe"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Kisisel Gelisim",
                            Slug = "kisisel-gelisim"
                        });
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("IndirimliFiyat")
                        .HasColumnType("numeric");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<double>("Puan")
                        .HasColumnType("double precision");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Yayinevi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YorumSayisi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Siparis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.SiteAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KargoUcreti")
                        .HasColumnType("numeric");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MagazaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UcretsizKargoLimiti")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlari");
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Kitap", b =>
                {
                    b.HasOne("BagdasKitapDunyasi.API.Models.Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BagdasKitapDunyasi.API.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
